#!/usr/bin/env bash

echo "Determining rebar3 Templates directory"
if [ -x ./rebar3 ]; then
	TEMP_PATH=$(./rebar3 dirs template_dir)
else
	TEMP_PATH=$(rebar3 dirs template_dir)
fi
TEMP_PATH=$(echo -n "$TEMP_PATH")
echo "Template Path = $TEMP_PATH"

echo "Generating rebar.config for each backend"
cd templates/backends
./build_backend_configs.escript
cd ../..
mkdir -p "$TEMP_PATH/nitrogen"

echo "Deploying template files to $TEMP_PATH"
cp templates/nitrogen.template $TEMP_PATH/nitrogen
cp -R templates/common $TEMP_PATH/nitrogen/
cp -R templates/win $TEMP_PATH/nitrogen/
cp -R templates/backends $TEMP_PATH/nitrogen/
cat templates/nitrogen.template templates/win.template > $TEMP_PATH/nitrogen/nitrogen_win.template
echo "Templates Deployed"
