% Compile Nitrogen Files (assuming Nitrogen root is the parent directory.)
{ '../src/*', [
	{ i, "../include" },
	{ outdir, "../ebin" }
]}.

% Compile Quickstart files.
{ './src/*', [
	{ i, "./include" },
	{ i, "../include" },
	{ outdir, "./ebin" }
]}.
