{ './src/*', [debug_info,warn_unused_vars,
               warn_export_all,
               warn_export_vars,
               warn_shadow_vars,
               warn_unused_import,
               warn_unused_function,
               warn_bif_clash,
               warn_unused_record,
               warn_deprecated_function,
               warn_obsolete_guard,
               warn_untyped_record,
               warn_missing_spec,
               warn_missing_spec_all,
	{ i, "./include" },
	{ outdir, "./ebin" }
]}.

{ './test/src/*', [debug_info,warn_unused_vars,
               warn_export_all,
               warn_export_vars,
               warn_shadow_vars,
               warn_unused_import,
               warn_unused_function,
               warn_bif_clash,
               warn_unused_record,
               warn_deprecated_function,
               warn_obsolete_guard,
               warn_untyped_record,
               warn_missing_spec,
               warn_missing_spec_all,
        { i, "./include" },
        { outdir, "./test/ebin" }
]}.
