% Compile Quickstart files.
{ ["./src/*", "./src/*/*", "./src/*/*/*"], [
	{ i, "./include" },
	{ i, "../include" },
	{ i, "../deps/simple_bridge/include" },
	{ outdir, "./ebin" },
	debug_info
]}.

% Compile Nitrogen files.
{ ["../src/*", "../src/*/*", "../src/*/*/*"], [
	{ i, "../include" },
	{ i, "../deps/simple_bridge/include" },
	{ outdir, "../ebin" },
	debug_info
]}.

